languages:
  JavaScript: true
  Python: true
exclude_paths:
- "__unported__/*"
- "*/__manifest__.py"   # because this is fed to eval
- "*/migrations/*"     # without OpenUpgrade, repetitions can be necessary
